apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: nginx-mcs
spec:
  template:
    spec:
      selector:
        app: nginx
      ports:
      - name: web
        protocol: TCP
        port: 80
        targetPort: 80
